# Generated by Django 3.1 on 2020-08-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Invitation',
        ),
    ]
