# Generated by Django 3.1 on 2020-08-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_auto_20200824_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
