# Generated by Django 3.1 on 2020-08-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_auto_20200824_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
