# Generated by Django 3.1 on 2020-08-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionType', '0002_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
