# Generated by Django 3.1 on 2020-09-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeaccount',
            old_name='usesrname',
            new_name='username',
        ),
    ]
