# Generated by Django 3.1 on 2020-08-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirlessMonitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internetmonitor',
            old_name='company',
            new_name='employee',
        ),
    ]
