# Generated by Django 3.1 on 2020-08-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirlessMonitor', '0002_auto_20200819_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='vpnApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('password', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
