# Generated by Django 3.1 on 2020-09-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('wirlessMonitor', '0004_vpnfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetmonitor',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
