# Generated by Django 3.1 on 2020-08-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_companyacc'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyacc',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='companyacc',
            name='password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='companyacc',
            name='usesrname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='companyacc',
            name='company',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
