# Generated by Django 3.1 on 2020-08-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200819_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyAcco',
        ),
    ]
